In [13]:
from sklearn.preprocessing import KBinsDiscretizer

In [14]:
import pandas as pd

In [15]:
df = pd.read_csv("sample_dataset.csv").iloc[:,0:5].dropna()

In [16]:
df

mean radius  mean texture  mean perimeter  mean area  mean smoothness
2          19.69         21.25          130.00     1203.0          0.10960
3          11.42         20.38           77.58      386.1          0.14250
8          13.00         21.82           87.50      519.8          0.12730
13         15.85         23.95          103.70      782.7          0.08401
14         13.73         22.61           93.60      578.3          0.11310
..           ...           ...             ...        ...              ...
549        10.82         24.21           68.89      361.6          0.08192
550        10.86         21.48           68.51      360.5          0.07431
560        14.05         27.15           91.38      600.4          0.09929
564        21.56         22.39          142.00     1479.0          0.11100
567        20.60         29.33          140.10     1265.0          0.11780

[176 rows x 5 columns]

# Bins with uniform width

In [17]:
binner = KBinsDiscretizer(strategy = 'uniform', n_bins = 5)

In [18]:
binner.fit_transform(df)

<176x25 sparse matrix of type '<class 'numpy.float64'>'
	with 880 stored elements in Compressed Sparse Row format>

In [20]:
binner = KBinsDiscretizer(strategy = 'uniform', n_bins = 5, encode = 'onehot-dense')
binner.fit_transform(df)

array([[0., 0., 1., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 0., 1.],
       ...,
       [0., 1., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [21]:
binner = KBinsDiscretizer(strategy = 'uniform', n_bins = 5, encode = 'ordinal')
binner.fit_transform(df)

array([[2., 1., 2., 2., 2.],
       [0., 1., 0., 0., 4.],
       [1., 2., 1., 0., 4.],
       [1., 2., 1., 1., 1.],
       [1., 2., 1., 0., 3.],
       [2., 2., 2., 2., 2.],
       [1., 1., 1., 0., 2.],
       [0., 0., 0., 0., 2.],
       [2., 1., 2., 1., 3.],
       [1., 1., 1., 0., 2.],
       [2., 2., 2., 1., 3.],
       [2., 2., 2., 2., 1.],
       [1., 1., 1., 0., 1.],
       [1., 1., 1., 0., 2.],
       [2., 2., 2., 1., 1.],
       [1., 1., 1., 0., 2.],
       [2., 1., 2., 1., 2.],
       [0., 1., 0., 0., 1.],
       [2., 1., 2., 1., 3.],
       [1., 1., 1., 0., 1.],
       [0., 0., 0., 0., 2.],
       [0., 0., 0., 0., 0.],
       [1., 2., 1., 0., 3.],
       [0., 1., 0., 0., 2.],
       [0., 0., 0., 0., 2.],
       [1., 1., 1., 0., 2.],
       [1., 0., 1., 0., 4.],
       [3., 2., 3., 2., 4.],
       [0., 1., 0., 0., 2.],
       [1., 0., 1., 0., 4.],
       [1., 1., 1., 0., 0.],
       [0., 1., 0., 0., 3.],
       [2., 1., 2., 1., 2.],
       [2., 1., 2., 2., 1.],
       [1., 1.

# Binning using quantiles

In [29]:
binner = KBinsDiscretizer(strategy = 'quantile', n_bins = 3, encode = 'ordinal')

In [30]:
binner.fit_transform(df)

array([[2., 2., 2., 2., 2.],
       [0., 1., 0., 0., 2.],
       [1., 2., 1., 1., 2.],
       [2., 2., 2., 2., 0.],
       [1., 2., 1., 1., 2.],
       [2., 2., 2., 2., 1.],
       [1., 0., 1., 1., 2.],
       [0., 0., 0., 0., 1.],
       [2., 0., 2., 2., 2.],
       [1., 2., 1., 1., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 1.],
       [1., 1., 1., 1., 1.],
       [1., 2., 1., 1., 1.],
       [2., 2., 2., 2., 1.],
       [1., 1., 1., 1., 2.],
       [2., 1., 2., 2., 2.],
       [0., 1., 0., 0., 0.],
       [2., 1., 2., 2., 2.],
       [1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [1., 2., 1., 1., 2.],
       [0., 1., 0., 0., 2.],
       [0., 0., 0., 0., 1.],
       [1., 0., 1., 1., 1.],
       [1., 0., 1., 1., 2.],
       [2., 2., 2., 2., 2.],
       [0., 1., 0., 0., 1.],
       [1., 0., 1., 1., 2.],
       [1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 2.],
       [2., 1., 2., 2., 2.],
       [2., 1., 2., 2., 0.],
       [1., 0.

In [31]:
np.unique(binner.fit_transform(df)[:,0],return_counts=True)

(array([0., 1., 2.]), array([59, 58, 59]))

# Binning using K-Means

In [37]:
binner = KBinsDiscretizer(strategy = 'kmeans', n_bins = 10, encode = 'ordinal')

binner.fit_transform(df)

array([[6., 5., 6., 6., 5.],
       [1., 4., 1., 1., 9.],
       [2., 5., 2., 2., 8.],
       [4., 6., 4., 4., 2.],
       [3., 5., 3., 3., 6.],
       [6., 5., 6., 6., 4.],
       [2., 2., 2., 2., 5.],
       [0., 1., 0., 0., 4.],
       [5., 3., 5., 5., 6.],
       [4., 5., 3., 3., 5.],
       [5., 6., 5., 5., 7.],
       [6., 7., 6., 6., 3.],
       [2., 3., 2., 2., 3.],
       [3., 4., 2., 2., 4.],
       [6., 6., 6., 5., 3.],
       [2., 4., 2., 2., 5.],
       [6., 3., 6., 5., 5.],
       [1., 3., 1., 1., 2.],
       [6., 4., 5., 5., 6.],
       [2., 4., 2., 2., 1.],
       [0., 1., 0., 0., 4.],
       [0., 1., 0., 0., 1.],
       [2., 6., 2., 2., 6.],
       [0., 3., 0., 0., 5.],
       [0., 2., 0., 0., 4.],
       [3., 2., 3., 3., 4.],
       [3., 0., 2., 2., 8.],
       [7., 6., 7., 6., 8.],
       [0., 4., 0., 0., 4.],
       [2., 2., 2., 2., 9.],
       [3., 4., 3., 3., 1.],
       [1., 4., 1., 0., 6.],
       [6., 3., 5., 5., 5.],
       [6., 4., 6., 6., 2.],
       [4., 3.