In [52]:
from sklearn.preprocessing import FunctionTransformer

In [53]:
import pandas as pd

In [54]:
import numpy as np

In [55]:
df = pd.read_csv("sample_dataset.csv").iloc[:,0:3].dropna()

In [56]:
df

mean radius  mean texture  mean perimeter
1          20.57         17.77          132.90
2          19.69         21.25          130.00
3          11.42         20.38           77.58
5          12.45         15.70           82.57
7          13.71         20.83           90.20
..           ...           ...             ...
562        15.22         30.62          103.40
563        20.92         25.09          143.00
564        21.56         22.39          142.00
566        16.60         28.08          108.30
567        20.60         29.33          140.10

[385 rows x 3 columns]

In [57]:
transformer = FunctionTransformer(np.log)

In [58]:
transformer.fit_transform(df)

mean radius  mean texture  mean perimeter
1       3.023834      2.877512        4.889597
2       2.980111      3.056357        4.867534
3       2.435366      3.014554        4.351310
5       2.521721      2.753661        4.413646
7       2.618125      3.036394        4.502029
..           ...           ...             ...
562     2.722610      3.421653        4.638605
563     3.040706      3.222469        4.962845
564     3.070840      3.108614        4.955827
566     2.809403      3.335058        4.684905
567     3.025291      3.378611        4.942356

[385 rows x 3 columns]

In [59]:
transformer = FunctionTransformer(np.log, validate = True)

In [60]:
transformer.fit_transform(df)

array([[3.0238337 , 2.87751164, 4.88959697],
       [2.98011089, 3.0563569 , 4.86753445],
       [2.4353662 , 3.01455403, 4.35130966],
       ...,
       [3.07083975, 3.10861443, 4.95582706],
       [2.8094027 , 3.33505758, 4.68490515],
       [3.02529108, 3.37861088, 4.94235645]])

In [62]:
transformer = FunctionTransformer(lambda x : x*3, validate = True)

In [63]:
transformer.fit_transform(df)

array([[ 61.71,  53.31, 398.7 ],
       [ 59.07,  63.75, 390.  ],
       [ 34.26,  61.14, 232.74],
       ...,
       [ 64.68,  67.17, 426.  ],
       [ 49.8 ,  84.24, 324.9 ],
       [ 61.8 ,  87.99, 420.3 ]])

In [70]:
transformer = FunctionTransformer(lambda x,a : x*a, validate = True, kw_args={'a':4})

In [71]:
transformer.fit_transform(df)

array([[ 82.28,  71.08, 531.6 ],
       [ 78.76,  85.  , 520.  ],
       [ 45.68,  81.52, 310.32],
       ...,
       [ 86.24,  89.56, 568.  ],
       [ 66.4 , 112.32, 433.2 ],
       [ 82.4 , 117.32, 560.4 ]])

In [73]:
def f(x,a):
    return x*a

transformer = FunctionTransformer(f, validate = True, kw_args={'a':4}, accept_sparse=True)
transformer.fit_transform(df)

array([[ 82.28,  71.08, 531.6 ],
       [ 78.76,  85.  , 520.  ],
       [ 45.68,  81.52, 310.32],
       ...,
       [ 86.24,  89.56, 568.  ],
       [ 66.4 , 112.32, 433.2 ],
       [ 82.4 , 117.32, 560.4 ]])