In [33]:
import pandas as pd
import numpy as np

In [26]:
df = pd.read_csv("sample_dataset.csv")

In [27]:
X = df.iloc[:,0:3].dropna()

In [28]:
X

mean radius  mean texture  mean perimeter
1          20.57         17.77          132.90
2          19.69         21.25          130.00
3          11.42         20.38           77.58
5          12.45         15.70           82.57
7          13.71         20.83           90.20
..           ...           ...             ...
562        15.22         30.62          103.40
563        20.92         25.09          143.00
564        21.56         22.39          142.00
566        16.60         28.08          108.30
567        20.60         29.33          140.10

[385 rows x 3 columns]

# Normalization

0-1 scaling

In [29]:
from sklearn.preprocessing import MinMaxScaler

In [30]:
scaler = MinMaxScaler()

In [31]:
X_scaled = scaler.fit_transform(X)

In [32]:
X_scaled

array([[0.63004759, 0.27257355, 0.60432679],
       [0.58687012, 0.3902604 , 0.58368915],
       [0.18110004, 0.36083869, 0.21064617],
       ...,
       [0.67862225, 0.42881299, 0.66908625],
       [0.43525833, 0.62123774, 0.42926274],
       [0.63151955, 0.66351031, 0.65556504]])

In [36]:
np.apply_over_axes(np.max,X_scaled,0)

array([[1., 1., 1.]])

In [37]:
np.apply_over_axes(np.min,X_scaled,0)

array([[0., 0., 0.]])

# Standardization

In [38]:
from sklearn.preprocessing import StandardScaler

In [39]:
scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

In [40]:
X_scaled

array([[ 1.87149535, -0.35527432,  1.7252216 ],
       [ 1.61663638,  0.44774298,  1.6034021 ],
       [-0.77845877,  0.24698866, -0.59859036],
       ...,
       [ 2.1582117 ,  0.71080038,  2.10748279],
       [ 0.72173384,  2.02377982,  0.6918562 ],
       [ 1.88018373,  2.31221994,  2.02767001]])

In [41]:
np.apply_over_axes(np.mean,X_scaled,0)

array([[-5.53669664e-17, -2.86062660e-16, -1.84556555e-17]])

In [42]:
np.apply_over_axes(np.var,X_scaled,0)

array([[1., 1., 1.]])

# Robust scaling

In [43]:
from sklearn.preprocessing import RobustScaler

In [44]:
scaler = RobustScaler()

In [45]:
X_scaled = scaler.fit_transform(X)

In [46]:
X_scaled

array([[ 1.78484108, -0.18650089,  1.64689365],
       [ 1.56968215,  0.43161634,  1.54510355],
       [-0.45232274,  0.27708703, -0.29484029],
       ...,
       [ 2.02689487,  0.63410302,  1.96630397],
       [ 0.81418093,  1.64476021,  0.78343278],
       [ 1.79217604,  1.86678508,  1.8996139 ]])

In [47]:
np.apply_over_axes(np.median,X_scaled,0)

array([[0., 0., 0.]])

In [48]:
scaler.inverse_transform(X_scaled)

array([[ 20.57,  17.77, 132.9 ],
       [ 19.69,  21.25, 130.  ],
       [ 11.42,  20.38,  77.58],
       ...,
       [ 21.56,  22.39, 142.  ],
       [ 16.6 ,  28.08, 108.3 ],
       [ 20.6 ,  29.33, 140.1 ]])

In [49]:
X.head(3)

mean radius  mean texture  mean perimeter
1        20.57         17.77          132.90
2        19.69         21.25          130.00
3        11.42         20.38           77.58

In [55]:
np.corrcoef(X, rowvar=False)

array([[1.        , 0.33758444, 0.9977871 ],
       [0.33758444, 1.        , 0.34507004],
       [0.9977871 , 0.34507004, 1.        ]])

In [57]:
np.corrcoef(MinMaxScaler().fit_transform(X), rowvar=False)

array([[1.        , 0.33758444, 0.9977871 ],
       [0.33758444, 1.        , 0.34507004],
       [0.9977871 , 0.34507004, 1.        ]])

In [58]:
np.corrcoef(StandardScaler().fit_transform(X), rowvar=False)

array([[1.        , 0.33758444, 0.9977871 ],
       [0.33758444, 1.        , 0.34507004],
       [0.9977871 , 0.34507004, 1.        ]])

In [59]:
np.corrcoef(RobustScaler().fit_transform(X), rowvar=False)

array([[1.        , 0.33758444, 0.9977871 ],
       [0.33758444, 1.        , 0.34507004],
       [0.9977871 , 0.34507004, 1.        ]])